"""Add destination_id to blogs table

Revision ID: 4504a4464dd6
Revises: 
Create Date: 2025-11-10 18:52:46.400970

"""
from alembic import op  # pyright: ignore[reportMissingImports]
import sqlalchemy as sa  # pyright: ignore[reportMissingImports]


# revision identifiers, used by Alembic.
revision = '4504a4464dd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_blogs_destination_id', 'destinations', ['destination_id'], ['destination_id'])

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('billing_cycle', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_subscribed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_ai_queries', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_ai_queries')
        batch_op.drop_column('ai_credits')

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_column('email_subscribed')
        batch_op.drop_column('cancel_at_period_end')
        batch_op.drop_column('subscription_end')
        batch_op.drop_column('subscription_start')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('tier')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blogs_destination_id', type_='foreignkey')
        batch_op.drop_column('destination_id')

    # ### end Alembic commands ###